### ISSUE TITLE
Error after upgrade to python3

### ISSUE THREAD

**Issue by scherniavsky** [zalando-incubator/docker-locust#91]
After #87 and #88 I started to get errors with the locally built image:
```
Traceback (most recent call last):
  File "/usr/local/bin/locust", line 7, in <module>
    from locust.main import main
  File "/usr/local/lib/python3.5/dist-packages/locust/main.py", line 14, in <module>
    from . import events, runners, web
  File "/usr/local/lib/python3.5/dist-packages/locust/runners.py", line 13, in <module>
    from gevent.pool import Group
  File "/usr/local/lib/python3.5/dist-packages/gevent/pool.py", line 27, in <module>
    from gevent._imap import IMap
  File "/usr/local/lib/python3.5/dist-packages/gevent/_imap.py", line 227, in <module>
    import_c_accel(globals(), 'gevent.__imap')
  File "/usr/local/lib/python3.5/dist-packages/gevent/_util.py", line 105, in import_c_accel
    mod = importlib.import_module(cname)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "src/gevent/_queue.pxd", line 18, in init gevent.__imap
ValueError: gevent._queue.Queue has the wrong size, try recompiling. Expected 80, got 72
```

The PRs have been temporarily reverted until the issue is found.

**Comment by scherniavsky** [comment]
The issue re-appeared in the rollback image, but was gone after re-building it without any modifications.

**Comment by scherniavsky** [comment]
The error appears randomly probably due to some unstable python package(s).
docker-locust images are now tested before being pushed to production (https://github.com/zalando-incubator/docker-locust/pull/100, https://github.com/zalando-incubator/docker-locust/pull/102, https://github.com/zalando-incubator/docker-locust/pull/103, https://github.com/zalando-incubator/docker-locust/pull/104), which fixes the issue for now
